apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
resources:
  - namespace.yaml
  - data.yaml
  - payment-service.yaml
  - order-service.yaml
  - user-service.yaml
  - inventory-service.yaml
  - traffic-generator.yaml
