/** Turns a ScenarioSpec into a contract-shaped Investigation plus its recorded SSE stream. */
import type {
  AgentResult,
  Investigation,
  InvestigationStep,
  LiveEvent,
  Report,
} from "../../src/lib/api/schemas";
import { iso } from "./rng";
import { CAPABILITY, type AgentSpec, type ScenarioSpec } from "./types";

/** Recorded agent timings in the specs are compact; real runs take ~3× longer (UC-10: p50 < 90 s). */
export const TIME_SCALE = 3;

type EventDraft = { at: number; type: LiveEvent["type"]; agent: string | null; data: unknown };

const stepId = (s: ScenarioSpec, a: AgentSpec) =>
  `st-${s.id.toLowerCase()}-${a.agent}-r${a.round ?? 1}`;

export function renderMarkdown(inv: Investigation): string {
  const r = inv.report;
  if (!r) return "";
  const top = inv.hypotheses.find((h) => h.id === r.root_cause_hypothesis_id);
  const evidence = new Map(inv.results.flatMap((x) => x.evidence).map((e) => [e.id, e]));
  const lines: string[] = [
    `# Incident report: ${inv.incident.title}`,
    "",
    `- **Investigation:** ${inv.id} (${inv.incident.id})`,
    `- **Service:** ${inv.incident.service ?? "unknown"} · **Environment:** ${inv.incident.environment ?? "unknown"}`,
    `- **Severity:** ${r.severity} · **Confidence:** ${Math.round(r.confidence * 100)}%`,
    `- **Affected services:** ${r.affected_services.join(", ") || "none"}`,
    "",
    "## Summary",
    "",
    r.summary,
    "",
    "## Root cause",
    "",
    top
      ? `${top.statement} _(confidence ${Math.round(top.confidence * 100)}%)_`
      : "No root cause identified.",
    "",
  ];
  if (top) {
    lines.push("### Supporting evidence", "");
    for (const id of top.supporting_evidence_ids) {
      const e = evidence.get(id);
      if (e)
        lines.push(
          `- \`${id}\` (${e.kind}, ${e.source}): ${e.summary}${e.link ? ` [link](${e.link})` : ""}`,
        );
    }
    lines.push("");
  }
  lines.push("## Impact", "", r.impact, "", "## Timeline (UTC)", "");
  for (const t of inv.timeline)
    lines.push(`- ${t.timestamp.slice(11, 19)} ${t.description} _(${t.source})_`);
  lines.push("", "## Next steps", "");
  r.next_steps.forEach((s, i) => lines.push(`${i + 1}. ${s}`));
  if (r.open_questions.length) {
    lines.push("", "## Open questions", "");
    for (const q of r.open_questions) lines.push(`- ${q}`);
  }
  lines.push("", `_Generated by AI Incident Agents (${inv.mode} mode)._`);
  return lines.join("\n");
}

export function buildScenario(
  s: ScenarioSpec,
  ids: { investigation: string; incident: string },
): { investigation: Investigation; events: LiveEvent[] } {
  const t0 = s.created;
  const at = (ms: number) => t0 + ms * TIME_SCALE;

  const steps: InvestigationStep[] = s.agents.map((a) => ({
    id: stepId(s, a),
    agent: a.agent,
    objective: a.objective,
    round: a.round ?? 1,
    depends_on:
      (a.round ?? 1) > 1
        ? s.agents.filter((x) => (x.round ?? 1) === 1).map((x) => stepId(s, x))
        : [],
    status: a.status === "failed" ? "failed" : "done",
    started_at: iso(at(a.start)),
    finished_at: iso(at(a.start + a.duration)),
  }));

  const results: AgentResult[] = s.agents.map((a) => {
    let cursor = at(a.start) + 150;
    const tool_calls = a.tools.map(([tool, ms, args], i) => {
      const call = {
        id: `tc-${s.id.toLowerCase()}-${a.agent}-r${a.round ?? 1}-${i + 1}`,
        agent: a.agent,
        capability: CAPABILITY[a.agent],
        tool,
        arguments: args ?? {},
        status: "ok" as const,
        duration_ms: ms,
        result_chars: 800 + ((ms * 37) % 9000),
        error: null,
        started_at: iso(cursor),
      };
      cursor += ms + 120;
      return call;
    });
    return {
      task_id: stepId(s, a),
      agent: a.agent,
      agent_version: "1.0.0",
      status: a.status,
      summary: a.summary,
      findings: a.findings.map((f, i) => ({
        ...f,
        id: `fi-${s.id.toLowerCase()}-${a.agent}-r${a.round ?? 1}-${i + 1}`,
      })),
      evidence: a.evidence,
      signals: a.signals,
      suggested_followups: [],
      tool_calls,
      confidence: a.findings[0]?.confidence ?? null,
      model: "fake-llm",
      prompt_version: "v1",
      usage: { input_tokens: 0, output_tokens: 0, calls: 1 },
      duration_ms: a.duration * TIME_SCALE,
      error: null,
    };
  });

  const agentsEnd = Math.max(...s.agents.map((a) => a.start + a.duration));
  const rcaStart = agentsEnd + 300;
  const rankedAt = rcaStart + 1500;
  const reportAt = rankedAt + 900;
  const finishedAt = reportAt + 100;
  const duration_ms = finishedAt * TIME_SCALE;

  const investigation: Investigation = {
    id: ids.investigation,
    incident: {
      id: ids.incident,
      title: s.question,
      description: "",
      service: s.service,
      environment: s.environment,
      source: "user",
      created_at: iso(t0),
    },
    context: {
      question: s.question,
      service: s.service,
      environment: s.environment,
      time_range: { start: iso(s.windowStart), end: iso(s.windowEnd) },
      symptoms: s.symptoms,
    },
    status: "completed",
    steps,
    results,
    hypotheses: s.hypotheses,
    recommendations: s.recommendations,
    timeline: s.timeline,
    report: { ...s.report, markdown: "" },
    clarification_question: null,
    clarification_candidates: [],
    versions: { model: "fake-llm (replay)", prompts: "v1", dataset: "demo-1" },
    usage: { input_tokens: 0, output_tokens: 0, calls: results.length + 1 },
    duration_ms,
    created_at: iso(t0),
    completed_at: iso(at(finishedAt)),
    mode: "demo",
  };
  (investigation.report as Report).markdown = renderMarkdown(investigation);

  // ---- events ----
  const drafts: EventDraft[] = [];
  const push = (ms: number, type: EventDraft["type"], agent: string | null, data: unknown) =>
    drafts.push({ at: at(ms), type, agent, data });

  push(0, "investigation_started", null, { question: s.question });
  push(400, "plan_created", null, {
    context: investigation.context,
    steps: steps.map((st) => ({ ...st, status: "queued", started_at: null, finished_at: null })),
  });
  const rounds = [...new Set(s.agents.map((a) => a.round ?? 1))];
  for (const r of rounds) {
    const inRound = s.agents.filter((a) => (a.round ?? 1) === r);
    push(Math.min(...inRound.map((a) => a.start)) - 60, "round_started", null, {
      round: r,
      agents: inRound.map((a) => a.agent),
    });
  }
  s.agents.forEach((a, idx) => {
    const sid = stepId(s, a);
    const res = results[idx]!;
    push(a.start, "agent_started", a.agent, {
      step_id: sid,
      objective: a.objective,
      round: a.round ?? 1,
    });
    // spread tool calls over the first 70% of the run, evidence over the last 30%
    const n = a.tools.length;
    a.tools.forEach(([tool, ms], i) => {
      push(a.start + ((i + 1) * a.duration * 0.7) / (n + 1), "tool_called", a.agent, {
        step_id: sid,
        tool,
        status: "ok",
        duration_ms: ms,
      });
    });
    a.evidence.forEach((e, i) => {
      push(
        a.start + a.duration * (0.72 + (0.25 * (i + 1)) / (a.evidence.length + 1)),
        "evidence_added",
        a.agent,
        {
          step_id: sid,
          evidence: e,
        },
      );
    });
    push(a.start + a.duration, "agent_finished", a.agent, {
      step_id: sid,
      status: a.status,
      summary: a.summary,
      signals: a.signals,
      evidence_count: a.evidence.length,
      duration_ms: res.duration_ms,
      tokens: 0,
    });
  });
  push(rcaStart, "rca_started", "rca", {});
  push(rankedAt, "hypothesis_ranked", "rca", { hypotheses: s.hypotheses });
  push(reportAt, "report_ready", "rca", { report: investigation.report });
  push(finishedAt, "investigation_finished", null, { status: "completed", duration_ms });

  drafts.sort((a, b) => a.at - b.at);
  const events = drafts.map(
    (d, i) =>
      ({
        type: d.type,
        investigation_id: ids.investigation,
        timestamp: new Date(d.at).toISOString(),
        seq: i + 1,
        agent: d.agent,
        data: d.data,
      }) as LiveEvent,
  );
  return { investigation, events };
}
