"""Demo only: mirror an injected fault as real commits in the local sample Git repo.

Fault injection (``aiops.faults``) changes ConfigMaps and images directly with kubectl.
In a real company that change arrives through git, which is what the Code agent reads.
So, in the LOCAL demo, injecting a scenario also commits the same change to the sample
repo that git-mcp serves (``.data/sample-repo``, built by ``aiops seed repo``), with the
current timestamp, and reverting commits a ``git revert`` of it.

The commits are the scenario's own changes from :mod:`aiops.seed.git_repo` (the ones the
recorded Code-agent fixtures contain), e.g. S1: "tune db pool" by Jordan Lee
(``services/payment-service/config/app.yaml`` DB_POOL_SIZE "20" -> "2"), then "release
payment-service v1.8.2".

Safety: only a repo generated by ``aiops seed repo`` (it has the marker file) is ever
touched, nothing is pushed (the repo has no remote), and any git problem is logged and
skipped: it never blocks an injection or a revert. Opt out with
``AIOPS_FAULT_GIT_COMMITS=0`` (or ``aiops fault inject --no-git-commit``).
"""

from __future__ import annotations

import contextlib
import os
from collections.abc import Callable
from datetime import UTC, datetime, timedelta
from pathlib import Path

from aiops.seed.git_repo import (
    MARKER,
    SCENARIO_CHANGES,
    Author,
    Files,
    RepoBuilder,
    RepoSeedError,
)

SWITCH_VAR = "AIOPS_FAULT_GIT_COMMITS"
REPO_VAR = "AIOPS_FAULT_GIT_REPO"
OFF_VALUES = {"0", "false", "no", "off"}


def enabled() -> bool:
    return os.environ.get(SWITCH_VAR, "1").strip().lower() not in OFF_VALUES


def _identity(author: Author, when: datetime) -> dict[str, str]:
    stamp = when.isoformat()
    return {
        "GIT_AUTHOR_NAME": author.name,
        "GIT_AUTHOR_EMAIL": author.email,
        "GIT_AUTHOR_DATE": stamp,
        "GIT_COMMITTER_NAME": author.name,
        "GIT_COMMITTER_EMAIL": author.email,
        "GIT_COMMITTER_DATE": stamp,
    }


class DemoRepo:
    """The local sample repo that git-mcp reads (never a real repository)."""

    def __init__(
        self,
        path: Path,
        *,
        clock: Callable[[], datetime] = lambda: datetime.now(UTC),
        log: Callable[[str], None] = print,
    ) -> None:
        self.path = path
        self.clock = clock
        self.log = log

    @classmethod
    def for_root(cls, root: Path, log: Callable[[str], None] = print) -> DemoRepo | None:
        """``$AIOPS_FAULT_GIT_REPO`` or ``<root>/.data/sample-repo``; None when opted out."""
        if not enabled():
            return None
        path = Path(os.environ.get(REPO_VAR) or root / ".data" / "sample-repo").expanduser()
        return cls(path, log=log)

    def unusable(self) -> str | None:
        if not (self.path / ".git").is_dir():
            return f"no sample repo at {self.path} (build it: make seed-repo S=S0)"
        if not (self.path / ".git" / MARKER).is_file():
            return f"{self.path} was not generated by `aiops seed repo`; not touching it"
        return None

    def _tree(self, git: RepoBuilder) -> Files:
        return {rel: (self.path / rel).read_text() for rel in git.git("ls-files").splitlines()}

    def commit_fault(self, scenario: str) -> list[str]:
        """Commit the scenario's change(s) at the current time. Returns the new SHAs."""
        changes = [c for c in SCENARIO_CHANGES if c.scenario == scenario]
        if not changes:
            return []  # e.g. S5: an infrastructure outage, no code or config change
        reason = self.unusable()
        if reason:
            self.log(f"  - no git commit: {reason}")
            return []
        git = RepoBuilder(self.path)
        shas: list[str] = []
        try:
            files = self._tree(git)
            now = self.clock().astimezone(UTC).replace(microsecond=0)
            for i, change in enumerate(changes):
                before = dict(files)
                change.apply(files)
                if files == before:
                    self.log(
                        f"  - git: '{change.subject}' is already in {self.path} "
                        "(seeded for this scenario? rebuild it healthy: make seed-repo S=S0)"
                    )
                    continue
                git.write_tree(files)
                # The last change lands at "now"; earlier ones a few seconds before (order).
                identity = _identity(change.author, now - timedelta(seconds=len(changes) - 1 - i))
                git.git("add", "-A")
                message = ["-m", change.subject] + (["-m", change.body] if change.body else [])
                git.git("commit", "-q", *message, extra_env=identity)
                sha = git.git("rev-parse", "HEAD")
                for name in change.tags:  # -f: the same release may be injected again
                    label = name.replace("/", " ")
                    git.git("tag", "-f", "-a", name, "-m", label, sha, extra_env=identity)
                shas.append(sha)
                self.log(f"  - git commit {sha[:10]} '{change.subject}' by {change.author.name}")
        except (RepoSeedError, OSError) as exc:
            self.log(f"  - git commit skipped: {exc}")
        return shas

    def revert(self, shas: list[str]) -> list[str]:
        """``git revert`` the injected commits (newest first). Returns the revert SHAs."""
        if not shas:
            return []
        reason = self.unusable()
        if reason:
            self.log(f"  - no git revert: {reason}")
            return []
        git = RepoBuilder(self.path)
        try:
            head = git.git("rev-parse", "HEAD")
            author = next(
                (c.author for c in SCENARIO_CHANGES if c.subject == self._subject(git, shas[0])),
                Author("aiops demo", "aiops-demo@example.com"),
            )
            identity = _identity(author, self.clock().astimezone(UTC).replace(microsecond=0))
            git.git("revert", "--no-edit", *reversed(shas), extra_env=identity)
            new = git.git("rev-list", f"{head}..HEAD").splitlines()
        except RepoSeedError as exc:
            self.log(f"  - git revert skipped: {exc}")
            with contextlib.suppress(RepoSeedError):
                git.git("revert", "--abort")
            return []
        for sha in reversed(new):
            self.log(f"  - git commit {sha[:10]} '{self._subject(git, sha)}'")
        return list(reversed(new))

    @staticmethod
    def _subject(git: RepoBuilder, sha: str) -> str:
        return git.git("log", "-1", "--format=%s", sha)
